Maintenance page
BUMETCS673/project-team-6 pull request #28
Opened 2023-10-09 22:03 UTC by KristampsWong

Since #27 PR, I marge to this branch. The Manage Cars, Add Cars, Edit Cars, Car Information are connected with Backend now.

2023-10-09 22:08 UTC, KristampsWong commented on code/src/app/api/carInfo/route.ts
In order to remove any properties from the (frontend) data  object that have values of an empty string or null.

2023-10-09 22:10 UTC, KristampsWong commented on code/src/app/api/carInfo/route.ts
>      ) {
'If a new date for last maintenance change is provided, then a new mileage for the last maintenance change should also be provided.'
In order to make sure both mileage and date been provide.

2023-10-09 22:16 UTC, KristampsWong commented on code/src/app/api/carInfo/route.ts
Get previous mileage for DB. Becuase there is a situation, if user only changed mileage but not change maitenance info, the OilOverdue and TireOverDue would not update. So get previous mileage from db, and compare with current to check if overdue or not

2023-10-09 22:16 UTC, KristampsWong commented on code/src/app/api/carInfo/route.ts
Check if need maintenance

2023-10-09 22:18 UTC, KristampsWong commented on code/src/app/api/carInfo/route.ts
> +    Object.assign(filteredData, maintenanceStatus);
Check if need maintenance

2023-10-10 02:01 UTC, ncruz93 requested changes
You changed the logic of the maintenance calculation I implemented completed. There should be a date of next scheduled change automatically calculated so that the calendar can display it. Overdue is only when the initial date calculated had passed and the maintenance change was not completed. I don't think you should have overwritten all of my work. Refactoring/Cleaning it up is fine, but this is completely different and it no longer works. How were you planning to use this to populate the calendar?

2023-10-15 19:06 UTC, Alisa007 approved these changes

2023-10-16 02:20 UTC, closed without merging